[Xamarin.Android.Build.Tasks] Set .NET6 defaults for bindings projects.
xamarin/xamarin-android pull request #6066
Opened 2021-07-01 15:18 UTC by jpobst

Fixes: #4657.

2021-07-02 14:26 UTC, dellis1972 requested changes
This looks good :) 
We do need to document the three new properties in https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/building-apps/build-properties.md though as they are public. This is in addition to the docs you added here already.

2021-07-06 14:37 UTC, dellis1972 approved these changes

2021-07-06 16:26 UTC, jonathanpeppers approved these changes

2021-07-07 20:19 UTC, jonpryor commented
Time for our favorite past-time, [bikeshedding](https://en.wiktionary.org/wiki/bikeshedding) names!

The names in play: `$(AndroidEnableBindingInterfaceConstants)`, `$(AndroidEnableBindingNestedInterfaceTypes)`, `$(AndroidEnableBindingStaticAndDefaultInterfaceMethods)`.

The semantics are a tad odd with `$(AndroidEnableBindingInterfaceConstants)`, as the implication is that "interface constants" *weren't* previously bound.  But they were! This just changes *where* they're bound, from an "interface alternative" type that isn't the interface, to the interface itself; see also xamarin/java.interop@105d5443.

`$(AndroidEnableBindingStaticAndDefaultInterfaceMethods)` is in a *somewhat* similar boat, in that the "interface alternative" type could contain static methods, yet the name implies that they weren't supported at all.

Thus, I'm not fond of these names.  The actual semantic changes aren't hinted at; it's impossible to know what they actually mean without reading the docs.

I would instead suggest:

  * `$(AndroidBoundInterfacesContainConstants)` instead of `$(AndroidEnableBindingInterfaceConstants)`
  * `$(AndroidBoundInterfacesContainTypes)` instead of `$(AndroidEnableBindingNestedInterfaceTypes)`
  * `$(AndroidBoundInterfacesContainStaticAndDefaultInterfaceMethods)` instead of `$(AndroidEnableBindingStaticAndDefaultInterfaceMethods)`

Though I do wonder if we need *this* much granularity in a "public-facing" manner.  The real question is, are we emitting C#7-compatible interfaces, in which interfaces only contain properties, events and method declarations, or are we emitting C#8-required interfaces, in which interfaces can *also* contain fields, static methods, methods with bodies, nested types, etc.

Thus, should we "unify" them into a single property, e.g. `$(AndroidBoundInterfacesMimicJava)`? ("Mimic Java" because, as far as most are concerned, Java supported these language features before C#, and enabling these features cause our bindings to more closely mirror the original Java declarations.)

2021-07-08 13:42 UTC, jpobst commented
Capturing some discussion:
```
3:24 PM] jpobst: i think the name changes are fine, i believe the granularity is helpful if you want to move forward to C# 8, but might need to disable parts for backwards compatbility
[3:44 PM] jonathanpeppers: Users probably wouldn't ever turn these off, would they?
They just get opted into them for .NET 6
[3:44 PM] jpobst: correct, unless they are migrating and need to maintain backwards compat
[3:44 PM] jonathanpeppers: Maybe the other names could just be private (as an escape hatch), and we have a single $(AndroidBoundInterfacesMimicJava) property that covers most cases
[3:51 PM] jpobst: so like for all the migration documentation: https://github.com/xamarin/xamarin-android/pull/6066/files#diff-d3fc71da91b99201132a14e3e1179d3b2fcb4aa49f920793246a2b661fb3beacR73, would we not mention that you can turn off individual features? or would we document the private flags?
[3:52 PM] jonp: indeed, good question.
[3:54 PM] jonp: @jpobst: alternate take: instead of controlling whether e.g. IFoo.Bar is emitted, it should "always" be emitted in a net6 context.  Instead, the question is whether the Foo.Bar "interface alternative" is generated.
[3:54 PM] jonp: could we have it so that both can be done, with Foo.Bar emitted for compat purposes, and IFoo.Bar emitted because It's Good And Proper
[3:54 PM] jpobst: i think each of these features has a different answer for that
[3:55 PM] jpobst: like constants, yes, but nested types, no
[3:55 PM] jonp: hm, indeed
[3:56 PM] jonp: which suggests we do want the fine-grained control
```

2021-07-14 19:00 UTC, merged