Add .NET 6+ template for Android wear
xamarin/xamarin-android pull request #7013
Opened 2022-05-19 10:04 UTC by dellis1972

Fixes #7003

This speaks for itself, lets add a template for Wear applications.

2022-05-19 13:50 UTC, jonathanpeppers reviewed
Can we add this new template to this test?

https://github.com/xamarin/xamarin-android/blob/b250c04b09a2b725336ae6d6c5693e0b9f37e4cc/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs#L214-L215

2022-05-19 13:54 UTC, dellis1972 commented on src/Microsoft.Android.Templates/android-wear/AndroidApp1.csproj
> +    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.Core.UI" Version="1.0.0.14" />
I'll test with just the Wear package. This is based on the working project the customer provided.

2022-05-19 13:54 UTC, dellis1972 commented on src/Microsoft.Android.Templates/android-wear/AndroidManifest.xml
> +		<meta-data android:name="com.google.android.wearable.standalone" android:value="true" />
again, this is based on the customer template. I'll remove this.

2022-05-19 16:19 UTC, jonathanpeppers commented on src/Microsoft.Android.Templates/android-wear/Resources/values/strings.xml
> +    <string name="app_text">Hello, Android!</string>
Should it say:
```suggestion
    <string name="app_text">Hello, Android Wear!</string>
```

2022-05-19 16:19 UTC, jonathanpeppers approved these changes
Otherwise LGTM 👍

2022-05-19 16:49 UTC, jonpryor commented
The fundamental question is, do we actually want to provide a template for Wear *at all*?

Providing a template implies that it's "fit for purpose", is tested, is maintained, will continue to work.

Which, for starters, implies that we'd have a "WearOS 'device'" that we use as a target, as we do with Android emulators now.

Do we want to actually do that?

VSMac *used* to have a Wear template.  VSMac 17 *does not* have a Wear template.  I suspect VSWin should go the same way (remove the template), and I'm not entirely certain that *we* want to provide a template *either*.

2022-05-19 17:04 UTC, jonathanpeppers commented
A test fails:
```
  Failed DotNetNew("androidwear") [1 m 1 s]
  Error Message:
     /Users/runner/work/1/a/TestRelease/05-19_15.06.09/temp/DotNetNewandroidwear/build.log should have no MSBuild warnings.
```

2022-05-23 11:17 UTC, dellis1972 commented
> A test fails:
> 
> ```
>   Failed DotNetNew("androidwear") [1 m 1 s]
>   Error Message:
>      /Users/runner/work/1/a/TestRelease/05-19_15.06.09/temp/DotNetNewandroidwear/build.log should have no MSBuild warnings.
> ```

Had to ignore these warnings in the test. It the `XA4218` which is where we look up the `uses-library` stuff from an `AndroidManifest` in a library and check the sdk directory for them. In this case these files do not exists so we end up with this `XA4218` warning.

2022-05-23 11:18 UTC, dellis1972 commented
@jonpryor is it worth me adding a test step to  install and run the WearOS emulator and run a test on it? It works locally for me, so we could actually start testing at least the template on  the emulator during CI?

2022-05-27 00:21 UTC, jonpryor commented
@dellis1972 [asked](https://github.com/xamarin/xamarin-android/pull/7013#issuecomment-1134544212):

> is it worth me adding a test step to install and run the WearOS emulator and run a test on it?

*Yes*.  Yes it is.  If we provide this template at all ([see also](https://github.com/xamarin/xamarin-android/pull/7013#issuecomment-1131952593)), then we're implicitly/explicitly stating that the template is *supported* and *works*.  Consequently, we *should* ensure that this runs as expected on a WearOS emulator for testing.

2022-06-02 21:41 UTC, jonathanpeppers requested changes
If we get to a point we want to merge this, we should use the updated .NET-branded app icons here: https://github.com/xamarin/xamarin-android/pull/7065

2022-06-08 13:43 UTC, dellis1972 commented
> If we get to a point we want to merge this, we should use the updated .NET-branded app icons here: #7065

Icons have been updated 👍

2022-06-08 13:55 UTC, jonathanpeppers commented on src/Microsoft.Android.Templates/android-wear/AndroidManifest.xml
> +	<application android:allowBackup="true" android:icon="@mipmap/appicon" android:label="@string/app_name" android:supportsRtl="true" android:theme="@android:style/Theme.DeviceDefault">
Does this also need `android:roundIcon="@mipmap/appicon_round"`?

Like we have here:

https://github.com/xamarin/xamarin-android/blob/6b43af37bc57b7eea2a213ee15de037e61784a1c/src/Microsoft.Android.Templates/android/AndroidManifest.xml#L3

Would it also be worth sharing the icons in a single folder? And we can make the build pull them in for both templates?

2022-06-08 14:22 UTC, jonathanpeppers commented on src/Microsoft.Android.Templates/android-wear/AndroidManifest.xml
> +	<application android:allowBackup="true" android:icon="@mipmap/appicon" android:label="@string/app_name" android:supportsRtl="true" android:theme="@android:style/Theme.DeviceDefault">
I think it uses the same purple square `.png`, but a different `.xml`? Android then clips it to a circle.

2022-06-15 08:58 UTC, dellis1972 commented
/azp run

2022-07-05 16:01 UTC, merged