Add ability to disable android implicit usings
xamarin/xamarin-android pull request #7933
Opened 2023-04-02 09:31 UTC by Youssef1313

`ImplicitUsings` is a property used by the .NET SDK to generate https://github.com/dotnet/sdk/blob/b5fc2fd0c35b40c2bffc2ce8e0780a2398ae4305/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CSharp.props#L25-L34

Since the same property is used here too, there is direct no way to say "I want the usings from the .NET SDK, but not from Android". One would have to give up using `ImplicitUsings` and add these manually:

```xml
    <Using Include="System" />
    <Using Include="System.Collections.Generic" />
    <Using Include="System.IO" />
    <Using Include="System.Linq" />
    <Using Include="System.Net.Http" />
    <Using Include="System.Threading" />
    <Using Include="System.Threading.Tasks" />
```

This PR allows to set `<AndroidDisableImplicitUsings>true</AndroidDisableImplicitUsings>` so that the `System.*` ones are produced, but not the Android ones.

2023-04-02 14:47 UTC, Youssef1313 commented
@jonathanpeppers @dellis1972 In case this will be expected, is there a similar change to be done in xamarin-macios repo?

2023-04-02 14:57 UTC, Youssef1313 commented on src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props
> +  <ItemGroup Condition=" '$(TargetPlatformIdentifier)' == 'android' and 'AndroidDisableImplicitUsings' != 'true' and $([MSBuild]::VersionEquals($(TargetFrameworkVersion), '8.0')) and ('$(ImplicitUsin
Probably should rename this to `XamarinDisableImplicitUsings` and use it [here](https://github.com/xamarin/xamarin-macios/blob/1fd05057ed96083fc70ba0f0afb8bb544592ad3b/dotnet/targets/Microsoft.Sdk.ImplicitNamespaceImports.template.props#L25) as well?

2023-04-10 18:51 UTC, Youssef1313 commented on src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props
> +  <ItemGroup Condition=" '$(TargetPlatformIdentifier)' == 'android' and 'AndroidDisableImplicitUsings' != 'true' and $([MSBuild]::VersionEquals($(TargetFrameworkVersion), '8.0')) and ('$(ImplicitUsin
https://github.com/xamarin/xamarin-macios/pull/18017

2023-04-10 19:18 UTC, jonathanpeppers requested changes
I believe you already can do what you want here, without any changes. For example, the MAUI workload removes Android implicit usings by doing:

https://github.com/dotnet/maui/blob/523653d099842fa17285cdd92882ed202465d791/src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/Microsoft.Maui.Controls.Build.Tasks.After.targets#L10-L13

You should be able to put in your `.csproj` file:

```xml
<Using Remove="@(Using->WithMetadataValue('Platform', 'Android'))" />
```

If we want to introduce new, standard MSBuild properties, we should first start with a design that describes how this feature should work across all optional workloads:

https://github.com/dotnet/designs

2023-04-10 19:39 UTC, Youssef1313 commented
It might not be worth it given there is a one-liner workaround.

2023-04-10 19:39 UTC, closed without merging